const ActionTypes = {
    ADD_COUNTER: "ADD_COUNTER",
    MINUS_COUNTER: "MINUS_COUNTER",

    GET_PRODUCT : "GET_PRODUCT",
    GET_PRODUCT_LOADING : "GET_PRODUCT_LOADING",
    GET_PRODUCT_FAIL : "GET_PRODUCT_FAIL",

    ADD_TO_CART : "ADD_TO_CART" ,
    REMOVE_TO_CART : "REMOVE_TO_CART",
    ADDER : "ADDER",

}
export {ActionTypes}